# Generated by Django 3.1 on 2021-01-23 19:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Advertiser',
            fields=[
                ('Advertiser_name', models.CharField(default='', max_length=200)),
                ('Advertiser_id', models.IntegerField(default=0, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Ad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('link', models.CharField(max_length=200)),
                ('img_url', models.CharField(max_length=200)),
                ('advertiser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Advertiser_management.advertiser')),
            ],
        ),
    ]
