# Generated by Django 3.1 on 2021-01-22 15:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BaseAdvertiser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Ad',
            fields=[
                ('baseadvertiser_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Advertiser_management.baseadvertiser')),
            ],
            bases=('Advertiser_management.baseadvertiser', models.Model),
        ),
        migrations.CreateModel(
            name='Advertiser',
            fields=[
                ('baseadvertiser_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Advertiser_management.baseadvertiser')),
            ],
            bases=('Advertiser_management.baseadvertiser', models.Model),
        ),
    ]
