# Generated by Django 3.1 on 2021-01-30 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Advertiser_management', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ad',
            name='approve',
        ),
    ]
