# Generated by Django 3.1 on 2021-01-24 06:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Advertiser_management', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='advertiser',
            old_name='advertiser_name',
            new_name='name',
        ),
    ]
