# Generated by Django 3.1 on 2021-01-30 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Advertiser_management', '0002_remove_ad_approve'),
    ]

    operations = [
        migrations.AddField(
            model_name='ad',
            name='approve',
            field=models.BooleanField(default=False, editable=False),
        ),
    ]
