# Generated by Django 3.1 on 2021-01-24 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Advertiser_management', '0002_auto_20210124_0933'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='img',
            field=models.URLField(),
        ),
    ]
