# Generated by Django 3.1 on 2021-01-31 15:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Advertiser_management', '0003_ad_approve'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='click',
            name='ad_id',
        ),
        migrations.RemoveField(
            model_name='view',
            name='ad_id',
        ),
        migrations.AddField(
            model_name='click',
            name='ad',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='Advertiser_management.ad'),
        ),
        migrations.AddField(
            model_name='view',
            name='ad',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='Advertiser_management.ad'),
        ),
        migrations.AlterField(
            model_name='ad',
            name='approve',
            field=models.BooleanField(default=False),
        ),
    ]
