# Generated by Django 3.1 on 2021-01-24 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Advertiser_management', '0003_auto_20210124_0935'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='img',
            field=models.ImageField(upload_to=''),
        ),
    ]
