# Generated by Django 3.1 on 2021-01-24 08:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Advertiser_management', '0005_auto_20210124_0951'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ad',
            old_name='img',
            new_name='image',
        ),
    ]
